#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#

# disable autocorrect
unsetopt correct_all
unsetopt correct

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# disable wildcard match for zsh. does not work well with wildcard search
unsetopt nomatch

# aliases
if [[ -s "${ZDOTDIR:-$HOME}/.aliases"  ]]; then
    source "${ZDOTDIR:-$HOME}/.aliases"
fi
if [[ -s "${ZDOTDIR:-$HOME}/.aliases.local"  ]]; then
    source "${ZDOTDIR:-$HOME}/.aliases.local"
fi

# exports
if [[ -s "${ZDOTDIR:-$HOME}/.exports"  ]]; then
    source "${ZDOTDIR:-$HOME}/.exports"
fi


# added by travis gem
#[ -f /Users/tave/.travis/travis.sh ] && source /Users/tave/.travis/travis.sh

# vi 
bindkey -M viins 'jj' vi-cmd-mode
bindkey "^R" history-incremental-search-backward

# autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh  ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

EDITOR='nvim'
VISUAL='nvim'

