#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# disable wildcard match for zsh. does not work well with wildcard search
unsetopt nomatch

# init docker
eval `boot2docker shellinit 2>/dev/null`
docker-up() {
    if [ $(boot2docker status) != 'running' ]; then
        boot2docker up
    fi
    eval `boot2docker shellinit 2>/dev/null`
}

# aliases
if [[ -s "${ZDOTDIR:-$HOME}/.aliases"  ]]; then
    source "${ZDOTDIR:-$HOME}/.aliases"
fi

# exports
if [[ -s "${ZDOTDIR:-$HOME}/.exports"  ]]; then
    source "${ZDOTDIR:-$HOME}/.exports"
fi

